name: Build Inkify Binaries and Installers

on:
  push:
    branches: [ "main","develop" ]
    tags: [ "v*" ] # Triggers the pipeline when you push a version tag (e.g., v1.0.0)
  workflow_dispatch: # Allows you to run it manually from the GitHub UI

env:
  AWS_REGION: ap-south-1
  S3_BUCKET: inkify-installers

jobs:
  build:
    name: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    # Run three parallel jobs on different operating systems
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache : 'pip'

    - name: Install Base Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Windows Build (Binary + Installer)
    # Build Binary files (CI - Runs on Branches & Tags)
    - name:  Windows Specific Dependencies and Build Windows Binary Executable file
      if: matrix.os == 'windows-latest'
      run: | 
        pip install pywin32
        pyinstaller --name inkify-agent --onefile --hidden-import win32timezone main.py

    # Package the executable into an installer using Inno Setup (CI - Runs on Branches & Tags)
    - name: Package Windows Installer (Inno Setup)
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        mkdir installer
        copy dist\inkify-agent.exe installer\
        copy system\windows\inkify-agent-service.exe installer\
        copy system\windows\inkify-agent-service.xml installer\
        copy system\windows\setup.iss installer\
        choco install innosetup --yes
        cd installer
        "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

    # Upload to Github Artifacts (CI - Runs on Branches & Tags)
    - name: Upload Windows Installer
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: InkifySetup
        path: installer/Output/*.exe

    # macOS Build (Binary + Installer)
    # Build Binary files (CI - Runs on Branches & Tags)
    - name: Build macOS Binary Executable file
      if: matrix.os == 'macos-latest'
      run: pyinstaller --name inkify-agent --onefile main.py

    # Package the executable into a .pkg installer using a shell script (CI - Runs on Branches & Tags)
    - name: Package macOS Installer (.pkg)
      if: matrix.os == 'macos-latest'
      run: |
        chmod +x scripts/build-mac-pkg.sh
        ./scripts/build-mac-pkg.sh

    # Upload to Github Artifacts (CI - Runs on Branches & Tags)
    - name: Upload macOS Installer
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: InkifyAgentPkg
        path: "*.pkg"

    # Linux Build (Binary + Installer)
    # Build Binary files (CI - Runs on Branches & Tags)
    - name: Build Linux Binary Executable file
      if: matrix.os == 'ubuntu-latest'
      run: pyinstaller --name inkify-agent --onefile main.py

    # Package the executable into a .deb installer using a shell script (CI - Runs on Branches & Tags)
    - name: Package Linux Installer (.deb)
      if: matrix.os == 'ubuntu-latest'
      run: |
        chmod +x scripts/build-linux-deb.sh
        ./scripts/build-linux-deb.sh
        
      # Upload to Github Artifacts (CI - Runs on Branches & Tags)
    - name: Upload Linux Installer
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: InkifyAgentDeb
        path: "*.deb"
    
    # Upload to AWS S3 & Release to Github
    # Determine S3 routing (CD - ONLY runs on Tags)
  release:
    name: Deploy to S3 and Release to Github
    needs: build # This forces the release job to wait until all 3 OS builds are done
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
  
    # Download all the artifacts
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: final-release-files
      - name: Set Deployment Variables
        id: set-env
        shell: bash
        run: |
          # If the tag contains '-beta' (e.g., v1.1.0-beta)
          if [[ "${{ github.ref }}" == *-beta* ]]; then
            echo "S3_PREFIX=beta/" >> $GITHUB_ENV
            echo "IS_PRERELEASE=true" >> $GITHUB_ENV
          # If it is a stable production tag (e.g., v1.1.0)
          else
            echo "S3_PREFIX=releases/" >> $GITHUB_ENV
            echo "IS_PRERELEASE=false" >> $GITHUB_ENV
          fi
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Upload (CD - ONLY runs on Tags)
      - name: Upload Installer to S3 (Windows, macOS, Linux)
        shell: bash
        run: |
          # Upload Windows Installer to S3 
          aws s3 cp final-release-files/InkifySetup/InkifySetup.exe s3://${{ env.S3_BUCKET }}/${{ env.S3_PREFIX }}windows/${{ github.ref_name }}/InkifySetup.exe
          
          # Upload macOS Installer to S3 
          aws s3 cp final-release-files/InkifyAgentPkg/*.pkg s3://${{ env.S3_BUCKET }}/${{ env.S3_PREFIX }}mac/${{ github.ref_name }}/InkifyAgent.pkg      
          
          # Upload Linux Installer to S3 
          aws s3 cp final-release-files/InkifyAgentDeb/*.deb s3://${{ env.S3_BUCKET }}/${{ env.S3_PREFIX }}linux/${{ github.ref_name }}/inkify-agent.deb

      # Create GitHub Release (CD - ONLY runs on Tags)
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: final-release-files/**/* # Grabs every file downloaded
          prerelease: ${{ env.IS_PRERELEASE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}